export const INDENT = {
  xxxxs: '4px',
  xxxs: '8px',
  xxs: '12px',
  xs: '16px',
  s: '20px',
  sm: '24px',
  m: '32px',
  l: '40px',
  xl: '48px',
  xxl: '58px',
  xxxl: '64px',
  none: '0px',
  auto: 'auto',
} as const;
